version: "3"
services:
    bot_core_ai_service:
        build: core
        ports:
            - "5005:5005"
        volumes:
            # - core/:/src
            - core/out.log:/src/out.log
            - core/models/:/src/models/
        networks:
            - stop-hate

    bot_backend_service:
        build: backend
        ports:
            - "5000:5000"
        depends_on:
            - bot_core_ai_service
        volumes:
            - ./backend:/app
        environment:
            FLASK_ENV: development
            RASA_URL: 'http://bot_core_ai_service:5005'
        networks:
            - stop-hate

networks:
    stop-hate:
        driver: bridge